import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787415596572 implements MigrationInterface {
    name = 'InitialSchema1787415596572'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_oauth_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" character varying(50) NOT NULL, "provider_id" character varying(255) NOT NULL, "access_token" text, "refresh_token" text, "profile_data" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_provider_providerId" UNIQUE ("provider", "provider_id"), CONSTRAINT "PK_5ef571183889c426bf38c22bb3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."organization_invitations_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TYPE "public"."organization_invitations_status_enum" AS ENUM('pending', 'accepted', 'expired', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "organization_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "email" character varying(255) NOT NULL, "role" "public"."organization_invitations_role_enum" NOT NULL DEFAULT 'member', "token" character varying(255) NOT NULL, "status" "public"."organization_invitations_status_enum" NOT NULL DEFAULT 'pending', "invited_by_user_id" uuid, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_at" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7dfa5b36a9305efc5b7e9f369a3" UNIQUE ("token"), CONSTRAINT "UQ_organization_invitation_email" UNIQUE ("organization_id", "email"), CONSTRAINT "PK_f172f12b8a9ee6584b661f57e24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7dfa5b36a9305efc5b7e9f369a" ON "organization_invitations" ("token") `);
        await queryRunner.query(`CREATE TABLE "msme_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "businessCategory" character varying(100), "industry" character varying(100), "gstin" character varying(15), "pan" character varying(10), "udyam_number" character varying(50), "address" text, "city" character varying(100), "state" character varying(100), "country" character varying(100), "postal_code" character varying(20), "employee_count" integer, "annual_turnover" numeric(15,2), "year_established" integer, "is_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_41f79f9f15398d082a83cd27a41" UNIQUE ("organization_id"), CONSTRAINT "UQ_1fff4b4cbea246b73b6f925495b" UNIQUE ("gstin"), CONSTRAINT "UQ_151a19e8bc67f84cfd2b43868b2" UNIQUE ("pan"), CONSTRAINT "UQ_fefbff4ebe8d0c7346dd3faece0" UNIQUE ("udyam_number"), CONSTRAINT "REL_41f79f9f15398d082a83cd27a4" UNIQUE ("organization_id"), CONSTRAINT "PK_c0518f1013a08901308577d64ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "msme_certifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "certificate_type" character varying(100) NOT NULL, "certificate_number" character varying(100) NOT NULL, "issuing_authority" character varying(255) NOT NULL, "issued_at" date NOT NULL, "expires_at" date, "document_url" text, "remarks" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c965fceef6f543f8026d80a3379" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_msme_certification_active" ON "msme_certifications" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_msme_certification_organization" ON "msme_certifications" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "registrationNumber" character varying(100), "taxId" character varying(100), "website" character varying(255), "logoUrl" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b7ca6d30b94fef571cff876884" UNIQUE ("name"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."organization_members_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "organization_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."organization_members_role_enum" NOT NULL DEFAULT 'member', "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_organization_user" UNIQUE ("organization_id", "user_id"), CONSTRAINT "PK_c2b39d5d072886a4d9c8105eb9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "avatarUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tender_sources_authentication_type_enum" AS ENUM('none', 'api_key', 'oauth2', 'basic', 'bearer')`);
        await queryRunner.query(`CREATE TABLE "tender_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "code" character varying(50) NOT NULL, "description" text, "base_url" character varying(512), "country" character varying(100) NOT NULL DEFAULT 'India', "is_active" boolean NOT NULL DEFAULT true, "supports_incremental_sync" boolean NOT NULL DEFAULT false, "sync_frequency_minutes" integer NOT NULL DEFAULT '360', "last_successful_sync_at" TIMESTAMP WITH TIME ZONE, "last_failed_sync_at" TIMESTAMP WITH TIME ZONE, "last_sync_duration_ms" integer, "authentication_type" "public"."tender_sources_authentication_type_enum" NOT NULL DEFAULT 'none', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6d2c386db4812dc375b54ad03fb" UNIQUE ("code"), CONSTRAINT "UQ_tender_source_code" UNIQUE ("code"), CONSTRAINT "PK_c7d724dd30eb5fceb9569aea0bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d2c386db4812dc375b54ad03f" ON "tender_sources" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_source_auth_type" ON "tender_sources" ("authentication_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_source_country" ON "tender_sources" ("country") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_source_active" ON "tender_sources" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "tender_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "code" character varying(50) NOT NULL, "slug" character varying(180) NOT NULL, "description" text, "parent_category_id" uuid, "display_order" integer NOT NULL DEFAULT '0', "icon" character varying(255), "color" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_225c5f7cb2d5226595053864cf6" UNIQUE ("slug"), CONSTRAINT "UQ_tender_category_code" UNIQUE ("code"), CONSTRAINT "UQ_tender_category_name" UNIQUE ("name"), CONSTRAINT "PK_cc03867303bc28cc7c9c42d3c7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09044ebe817cccdbcb1183468b" ON "tender_categories" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_fad5d6f20bd53891d842d02459" ON "tender_categories" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_parent" ON "tender_categories" ("parent_category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_display_order" ON "tender_categories" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_active" ON "tender_categories" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."tenders_tender_type_enum" AS ENUM('open', 'limited', 'single', 'global')`);
        await queryRunner.query(`CREATE TYPE "public"."tenders_status_enum" AS ENUM('draft', 'published', 'active', 'evaluation', 'awarded', 'cancelled', 'closed')`);
        await queryRunner.query(`CREATE TABLE "tenders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "title" character varying(500) NOT NULL, "reference_number" character varying(150) NOT NULL, "description" text, "source" character varying(150), "procurement_category" character varying(150), "tender_type" "public"."tenders_tender_type_enum" NOT NULL DEFAULT 'open', "estimated_value" numeric(15,2), "currency" character varying(10) NOT NULL DEFAULT 'INR', "publish_date" TIMESTAMP WITH TIME ZONE, "submission_deadline" TIMESTAMP WITH TIME ZONE, "opening_date" TIMESTAMP WITH TIME ZONE, "issuing_authority" character varying(255), "location" character varying(255), "status" "public"."tenders_status_enum" NOT NULL DEFAULT 'published', "document_url" text, "created_by_user_id" uuid, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7a4ba8e81b180c9c248b30877c1" UNIQUE ("reference_number"), CONSTRAINT "PK_13fdd4229818a97b5102199463b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a4ba8e81b180c9c248b30877c" ON "tenders" ("reference_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_462fa4960a4caa39f683ed4868" ON "tenders" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."tender_category_links_assignment_source_enum" AS ENUM('manual', 'ai', 'imported')`);
        await queryRunner.query(`CREATE TABLE "tender_category_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tender_id" uuid NOT NULL, "category_id" uuid NOT NULL, "is_primary_category" boolean NOT NULL DEFAULT false, "confidence_score" numeric(5,2), "assigned_by_user_id" uuid, "assigned_at" TIMESTAMP WITH TIME ZONE, "assignment_source" "public"."tender_category_links_assignment_source_enum" NOT NULL DEFAULT 'manual', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_tender_category_pair" UNIQUE ("tender_id", "category_id"), CONSTRAINT "PK_810f0a29a9bec36220a4ac9d8e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_link_primary" ON "tender_category_links" ("is_primary_category") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_link_category" ON "tender_category_links" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_category_link_tender" ON "tender_category_links" ("tender_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tender_documents_storage_provider_enum" AS ENUM('local', 's3', 'azure', 'gcs')`);
        await queryRunner.query(`CREATE TABLE "tender_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tender_id" uuid NOT NULL, "original_file_name" character varying(255) NOT NULL, "stored_file_name" character varying(255) NOT NULL, "file_path" text NOT NULL, "file_type" character varying(100) NOT NULL, "file_size" bigint NOT NULL, "checksum" character varying(128), "uploaded_by_user_id" uuid, "storage_provider" "public"."tender_documents_storage_provider_enum" NOT NULL DEFAULT 's3', "is_processed" boolean NOT NULL DEFAULT false, "processed_at" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_19a19622716a9ad5349f195e582" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_processed" ON "tender_documents" ("is_processed") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_uploaded_by" ON "tender_documents" ("uploaded_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_tender" ON "tender_documents" ("tender_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tender_field_corrections_correction_source_enum" AS ENUM('manual', 'ai', 'imported')`);
        await queryRunner.query(`CREATE TABLE "tender_field_corrections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tender_id" uuid NOT NULL, "field_name" character varying(150) NOT NULL, "original_value" text, "corrected_value" text NOT NULL, "correction_reason" text, "corrected_by_user_id" uuid, "correction_source" "public"."tender_field_corrections_correction_source_enum" NOT NULL DEFAULT 'manual', "confidence_before" numeric(5,2), "confidence_after" numeric(5,2), "metadata" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_85f13f6b7b2209901c6c85ce654" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_tender_field_correction_source" ON "tender_field_corrections" ("correction_source") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_field_correction_field" ON "tender_field_corrections" ("field_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_field_correction_tender" ON "tender_field_corrections" ("tender_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ingestion_runs_status_enum" AS ENUM('pending', 'running', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."ingestion_runs_trigger_type_enum" AS ENUM('scheduled', 'manual', 'webhook')`);
        await queryRunner.query(`CREATE TABLE "ingestion_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tender_source_id" uuid NOT NULL, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "status" "public"."ingestion_runs_status_enum" NOT NULL DEFAULT 'pending', "total_fetched" integer NOT NULL DEFAULT '0', "total_created" integer NOT NULL DEFAULT '0', "total_updated" integer NOT NULL DEFAULT '0', "total_skipped" integer NOT NULL DEFAULT '0', "total_failed" integer NOT NULL DEFAULT '0', "duration_ms" integer, "retry_count" integer NOT NULL DEFAULT '0', "trigger_type" "public"."ingestion_runs_trigger_type_enum" NOT NULL DEFAULT 'scheduled', "initiated_by_user_id" uuid, "metadata" jsonb, "error_summary" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e9476c02c52a0dac026b859858a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_run_completed_at" ON "ingestion_runs" ("completed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_run_started_at" ON "ingestion_runs" ("started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_run_status" ON "ingestion_runs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_run_source" ON "ingestion_runs" ("tender_source_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ingestion_errors_severity_enum" AS ENUM('info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TABLE "ingestion_errors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ingestion_run_id" uuid NOT NULL, "tender_source_id" uuid NOT NULL, "severity" "public"."ingestion_errors_severity_enum" NOT NULL DEFAULT 'error', "error_code" character varying(100) NOT NULL, "error_message" text NOT NULL, "stack_trace" text, "external_reference" character varying(255), "payload" jsonb, "retryable" boolean NOT NULL DEFAULT false, "resolved" boolean NOT NULL DEFAULT false, "resolved_at" TIMESTAMP WITH TIME ZONE, "resolved_by_user_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_38adf14be2f594930880bf43547" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_error_resolved" ON "ingestion_errors" ("resolved") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_error_retryable" ON "ingestion_errors" ("retryable") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_error_severity" ON "ingestion_errors" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_error_source" ON "ingestion_errors" ("tender_source_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingestion_error_run" ON "ingestion_errors" ("ingestion_run_id") `);
        await queryRunner.query(`CREATE TABLE "tender_embeddings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_00e176f46f37efd4fa5b698d407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_profile_embeddings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_12b5e1efc0329f147c2d0b4392d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tender_document_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tender_document_id" uuid NOT NULL, "chunk_index" integer NOT NULL, "page_number" integer, "section_title" character varying(255), "content" text NOT NULL, "token_count" integer NOT NULL, "character_count" integer NOT NULL, "checksum" character varying(64) NOT NULL, "language" character varying(10) NOT NULL DEFAULT 'en', "metadata" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_tender_document_chunk_index" UNIQUE ("tender_document_id", "chunk_index"), CONSTRAINT "PK_60b5769fd6e1c62c505ca30a9cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_chunk_checksum" ON "tender_document_chunks" ("checksum") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_chunk_language" ON "tender_document_chunks" ("language") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_chunk_page" ON "tender_document_chunks" ("page_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_chunk_index" ON "tender_document_chunks" ("chunk_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_tender_document_chunk_document" ON "tender_document_chunks" ("tender_document_id") `);
        await queryRunner.query(`CREATE TABLE "tender_chunk_embeddings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_d352d093eb522d772dbeded5f78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "match_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_003d41d32629ae9faf61756c30c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eligibility_checklist_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_a9f9d4550e1a0143d3ea25a1ed3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pipeline_items_stage_enum" AS ENUM('DISCOVERED', 'REVIEWING', 'ELIGIBLE', 'BID_IN_PROGRESS', 'SUBMITTED', 'WON', 'LOST', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."pipeline_items_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "pipeline_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "tender_id" uuid NOT NULL, "stage" "public"."pipeline_items_stage_enum" NOT NULL DEFAULT 'DISCOVERED', "priority" "public"."pipeline_items_priority_enum" NOT NULL DEFAULT 'MEDIUM', "assigned_to_user_id" uuid, "due_date" TIMESTAMP WITH TIME ZONE, "notes" text, "is_archived" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ff6d7617fdace73e68a11fa47af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_pipeline_due_date" ON "pipeline_items" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_pipeline_priority" ON "pipeline_items" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_pipeline_stage" ON "pipeline_items" ("stage") `);
        await queryRunner.query(`CREATE INDEX "IDX_pipeline_tender" ON "pipeline_items" ("tender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_pipeline_organization" ON "pipeline_items" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."checklist_tasks_task_type_enum" AS ENUM('DOCUMENT', 'REVIEW', 'APPROVAL', 'PAYMENT', 'SUBMISSION', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."checklist_tasks_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."checklist_tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "checklist_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pipeline_item_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "task_type" "public"."checklist_tasks_task_type_enum" NOT NULL DEFAULT 'OTHER', "status" "public"."checklist_tasks_status_enum" NOT NULL DEFAULT 'PENDING', "priority" "public"."checklist_tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "assigned_to_user_id" uuid, "due_date" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f63da8740c5aea17102761665ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_sort_order" ON "checklist_tasks" ("sort_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_due_date" ON "checklist_tasks" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_priority" ON "checklist_tasks" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_status" ON "checklist_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_pipeline_item" ON "checklist_tasks" ("pipeline_item_id") `);
        await queryRunner.query(`CREATE TYPE "public"."bid_drafts_status_enum" AS ENUM('DRAFT', 'REVIEW', 'APPROVED', 'SUBMITTED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "bid_drafts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pipeline_item_id" uuid NOT NULL, "version" integer NOT NULL DEFAULT '1', "title" character varying(255) NOT NULL, "content" text NOT NULL, "generated_by_ai" boolean NOT NULL DEFAULT false, "status" "public"."bid_drafts_status_enum" NOT NULL DEFAULT 'DRAFT', "file_url" text, "submitted_at" TIMESTAMP WITH TIME ZONE, "created_by_user_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a9d9afceefdc50b550289d68da6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bid_draft_generated_by_ai" ON "bid_drafts" ("generated_by_ai") `);
        await queryRunner.query(`CREATE INDEX "IDX_bid_draft_version" ON "bid_drafts" ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_bid_draft_status" ON "bid_drafts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bid_draft_pipeline_item" ON "bid_drafts" ("pipeline_item_id") `);
        await queryRunner.query(`CREATE TYPE "public"."saved_searches_sort_direction_enum" AS ENUM('ASC', 'DESC')`);
        await queryRunner.query(`CREATE TABLE "saved_searches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "search_query" text NOT NULL, "filters" jsonb, "sort_by" character varying(100) NOT NULL DEFAULT 'createdAt', "sort_direction" "public"."saved_searches_sort_direction_enum" NOT NULL DEFAULT 'DESC', "notify_on_new_matches" boolean NOT NULL DEFAULT false, "is_default" boolean NOT NULL DEFAULT false, "last_executed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9a53c71ccc5cf66dcdc5b33dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_saved_search_last_executed" ON "saved_searches" ("last_executed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_saved_search_notify" ON "saved_searches" ("notify_on_new_matches") `);
        await queryRunner.query(`CREATE INDEX "IDX_saved_search_default" ON "saved_searches" ("is_default") `);
        await queryRunner.query(`CREATE INDEX "IDX_saved_search_name" ON "saved_searches" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_saved_search_organization" ON "saved_searches" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('SYSTEM', 'TENDER', 'BID', 'PAYMENT', 'REMINDER', 'SECURITY')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "user_id" uuid, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'SYSTEM', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'LOW', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "action_url" text, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notification_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_priority" ON "notifications" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_type" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_user" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_organization" ON "notifications" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_digest_frequency_enum" AS ENUM('NEVER', 'IMMEDIATE', 'DAILY', 'WEEKLY')`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "email_enabled" boolean NOT NULL DEFAULT true, "push_enabled" boolean NOT NULL DEFAULT true, "sms_enabled" boolean NOT NULL DEFAULT false, "tender_notifications" boolean NOT NULL DEFAULT true, "bid_notifications" boolean NOT NULL DEFAULT true, "payment_notifications" boolean NOT NULL DEFAULT true, "reminder_notifications" boolean NOT NULL DEFAULT true, "security_notifications" boolean NOT NULL DEFAULT true, "marketing_notifications" boolean NOT NULL DEFAULT false, "digest_frequency" "public"."notification_preferences_digest_frequency_enum" NOT NULL DEFAULT 'IMMEDIATE', "quiet_hours_start" character varying(5), "quiet_hours_end" character varying(5), "timezone" character varying(100) NOT NULL DEFAULT 'UTC', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notification_preference_push" ON "notification_preferences" ("push_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_preference_email" ON "notification_preferences" ("email_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_preference_digest" ON "notification_preferences" ("digest_frequency") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_notification_preference_user" ON "notification_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(100) NOT NULL, "description" text, "monthly_price" numeric(10,2) NOT NULL, "yearly_price" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "max_users" integer NOT NULL, "max_tenders_per_month" integer NOT NULL, "max_storage_gb" integer NOT NULL, "ai_credits_per_month" integer NOT NULL, "features" jsonb, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d2df70a81d37c893ef216caf8a" UNIQUE ("code"), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_subscription_plan_display_order" ON "subscription_plans" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_subscription_plan_active" ON "subscription_plans" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_subscription_plan_code" ON "subscription_plans" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."organization_subscriptions_status_enum" AS ENUM('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."organization_subscriptions_billing_cycle_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "organization_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "subscription_plan_id" uuid NOT NULL, "status" "public"."organization_subscriptions_status_enum" NOT NULL DEFAULT 'TRIAL', "billing_cycle" "public"."organization_subscriptions_billing_cycle_enum" NOT NULL DEFAULT 'MONTHLY', "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE, "next_billing_date" TIMESTAMP WITH TIME ZONE, "auto_renew" boolean NOT NULL DEFAULT true, "external_subscription_id" character varying(255), "payment_provider" character varying(100), "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_64e17f1dc8ebe056b49e751a494" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_org_subscription_next_billing" ON "organization_subscriptions" ("next_billing_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_org_subscription_billing_cycle" ON "organization_subscriptions" ("billing_cycle") `);
        await queryRunner.query(`CREATE INDEX "IDX_org_subscription_status" ON "organization_subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_org_subscription_plan" ON "organization_subscriptions" ("subscription_plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_org_subscription_organization" ON "organization_subscriptions" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'ISSUED', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_subscription_id" uuid NOT NULL, "invoice_number" character varying(255) NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "amount" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "payment_provider" character varying(100) NOT NULL, "external_invoice_id" character varying(255), "invoice_url" text, "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "due_at" TIMESTAMP WITH TIME ZONE NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_paid_at" ON "invoices" ("paid_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_due_at" ON "invoices" ("due_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_issued_at" ON "invoices" ("issued_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_status" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invoice_number" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_subscription" ON "invoices" ("organization_subscription_id") `);
        await queryRunner.query(`CREATE TABLE "usage_counters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "metric" character varying(255) NOT NULL, "usage_count" integer NOT NULL DEFAULT '0', "usage_limit" integer NOT NULL, "billing_period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "billing_period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "last_reset_at" TIMESTAMP WITH TIME ZONE NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fb39db314fa8fc2b6653f2f4e31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_usage_counter_period_end" ON "usage_counters" ("billing_period_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_usage_counter_period_start" ON "usage_counters" ("billing_period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_usage_counter_metric" ON "usage_counters" ("metric") `);
        await queryRunner.query(`CREATE INDEX "IDX_usage_counter_organization" ON "usage_counters" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "user_id" uuid, "action" character varying(255) NOT NULL, "resource_type" character varying(150) NOT NULL, "resource_id" uuid, "ip_address" character varying(45), "user_agent" text, "old_values" jsonb, "new_values" jsonb, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_resource_id" ON "audit_logs" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_resource_type" ON "audit_logs" ("resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_user" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_log_organization" ON "audit_logs" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."dsr_requests_request_type_enum" AS ENUM('EXPORT_DATA', 'DELETE_DATA', 'ANONYMIZE_DATA')`);
        await queryRunner.query(`CREATE TYPE "public"."dsr_requests_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "dsr_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "requested_by_user_id" uuid NOT NULL, "request_type" "public"."dsr_requests_request_type_enum" NOT NULL, "status" "public"."dsr_requests_status_enum" NOT NULL DEFAULT 'PENDING', "reason" text, "request_data" jsonb, "processed_by_user_id" uuid, "processed_at" TIMESTAMP WITH TIME ZONE, "completion_notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9ca35c097957361a800947e5f92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_created_at" ON "dsr_requests" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_status" ON "dsr_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_type" ON "dsr_requests" ("request_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_processed_by" ON "dsr_requests" ("processed_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_requested_by" ON "dsr_requests" ("requested_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dsr_request_organization" ON "dsr_requests" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "user_oauth_identities" ADD CONSTRAINT "FK_a0704331845bb831f82b54aea08" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_invitations" ADD CONSTRAINT "FK_7f88954e8d667a76ae3ced6f446" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "msme_profiles" ADD CONSTRAINT "FK_41f79f9f15398d082a83cd27a41" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "msme_certifications" ADD CONSTRAINT "FK_09054a14e0ffb0c677636d64e63" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_categories" ADD CONSTRAINT "FK_44dd4ea9994eb8eb1486031e449" FOREIGN KEY ("parent_category_id") REFERENCES "tender_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenders" ADD CONSTRAINT "FK_bc683384a04d34dff56d1bef0e5" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_category_links" ADD CONSTRAINT "FK_036255c28452f4fc26fae079eae" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_category_links" ADD CONSTRAINT "FK_9aca554b7839388cd4e08ce5b75" FOREIGN KEY ("category_id") REFERENCES "tender_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_documents" ADD CONSTRAINT "FK_d30f33a671c2aa29089c30b0a40" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_field_corrections" ADD CONSTRAINT "FK_80a1bc35b79c776d1cc8d3252ca" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingestion_runs" ADD CONSTRAINT "FK_c4d1b92a5a5ef3fb5bfd9ec75f2" FOREIGN KEY ("tender_source_id") REFERENCES "tender_sources"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingestion_errors" ADD CONSTRAINT "FK_66c3308e1a19e1961deb540e265" FOREIGN KEY ("ingestion_run_id") REFERENCES "ingestion_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingestion_errors" ADD CONSTRAINT "FK_f92dec35b71e743803bbbbee1cd" FOREIGN KEY ("tender_source_id") REFERENCES "tender_sources"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_document_chunks" ADD CONSTRAINT "FK_d49f4b063b87811c4603964a1ec" FOREIGN KEY ("tender_document_id") REFERENCES "tender_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pipeline_items" ADD CONSTRAINT "FK_89062c605117574da43058680bd" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pipeline_items" ADD CONSTRAINT "FK_11cc81882f3297fa4e7cd7ef265" FOREIGN KEY ("tender_id") REFERENCES "tenders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_tasks" ADD CONSTRAINT "FK_8a26959b79b1b9b69c969a7d14d" FOREIGN KEY ("pipeline_item_id") REFERENCES "pipeline_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bid_drafts" ADD CONSTRAINT "FK_f55c9ecbdf3d877ed2fe110c657" FOREIGN KEY ("pipeline_item_id") REFERENCES "pipeline_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_searches" ADD CONSTRAINT "FK_3b0957253925911ffe64de54d7c" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_cb7b1fb018b296f2107e998b2ff" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_subscriptions" ADD CONSTRAINT "FK_ee120ecc7d96135bd947a1ea7ae" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_subscriptions" ADD CONSTRAINT "FK_8aad2e6b2214d24ab18c0b13a2f" FOREIGN KEY ("subscription_plan_id") REFERENCES "subscription_plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_07ca7f7daf731dd48b29249ca63" FOREIGN KEY ("organization_subscription_id") REFERENCES "organization_subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_counters" ADD CONSTRAINT "FK_77beb529493148e94d370a00262" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_145f35b204c731ba7fc1a0be0e7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsr_requests" ADD CONSTRAINT "FK_9f7a8a764d5c1badb2dc3da2608" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsr_requests" ADD CONSTRAINT "FK_2ce564080f9ab54a3393252107b" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsr_requests" ADD CONSTRAINT "FK_d50153fa97583a4b4b4414629a1" FOREIGN KEY ("processed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dsr_requests" DROP CONSTRAINT "FK_d50153fa97583a4b4b4414629a1"`);
        await queryRunner.query(`ALTER TABLE "dsr_requests" DROP CONSTRAINT "FK_2ce564080f9ab54a3393252107b"`);
        await queryRunner.query(`ALTER TABLE "dsr_requests" DROP CONSTRAINT "FK_9f7a8a764d5c1badb2dc3da2608"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_145f35b204c731ba7fc1a0be0e7"`);
        await queryRunner.query(`ALTER TABLE "usage_counters" DROP CONSTRAINT "FK_77beb529493148e94d370a00262"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_07ca7f7daf731dd48b29249ca63"`);
        await queryRunner.query(`ALTER TABLE "organization_subscriptions" DROP CONSTRAINT "FK_8aad2e6b2214d24ab18c0b13a2f"`);
        await queryRunner.query(`ALTER TABLE "organization_subscriptions" DROP CONSTRAINT "FK_ee120ecc7d96135bd947a1ea7ae"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_cb7b1fb018b296f2107e998b2ff"`);
        await queryRunner.query(`ALTER TABLE "saved_searches" DROP CONSTRAINT "FK_3b0957253925911ffe64de54d7c"`);
        await queryRunner.query(`ALTER TABLE "bid_drafts" DROP CONSTRAINT "FK_f55c9ecbdf3d877ed2fe110c657"`);
        await queryRunner.query(`ALTER TABLE "checklist_tasks" DROP CONSTRAINT "FK_8a26959b79b1b9b69c969a7d14d"`);
        await queryRunner.query(`ALTER TABLE "pipeline_items" DROP CONSTRAINT "FK_11cc81882f3297fa4e7cd7ef265"`);
        await queryRunner.query(`ALTER TABLE "pipeline_items" DROP CONSTRAINT "FK_89062c605117574da43058680bd"`);
        await queryRunner.query(`ALTER TABLE "tender_document_chunks" DROP CONSTRAINT "FK_d49f4b063b87811c4603964a1ec"`);
        await queryRunner.query(`ALTER TABLE "ingestion_errors" DROP CONSTRAINT "FK_f92dec35b71e743803bbbbee1cd"`);
        await queryRunner.query(`ALTER TABLE "ingestion_errors" DROP CONSTRAINT "FK_66c3308e1a19e1961deb540e265"`);
        await queryRunner.query(`ALTER TABLE "ingestion_runs" DROP CONSTRAINT "FK_c4d1b92a5a5ef3fb5bfd9ec75f2"`);
        await queryRunner.query(`ALTER TABLE "tender_field_corrections" DROP CONSTRAINT "FK_80a1bc35b79c776d1cc8d3252ca"`);
        await queryRunner.query(`ALTER TABLE "tender_documents" DROP CONSTRAINT "FK_d30f33a671c2aa29089c30b0a40"`);
        await queryRunner.query(`ALTER TABLE "tender_category_links" DROP CONSTRAINT "FK_9aca554b7839388cd4e08ce5b75"`);
        await queryRunner.query(`ALTER TABLE "tender_category_links" DROP CONSTRAINT "FK_036255c28452f4fc26fae079eae"`);
        await queryRunner.query(`ALTER TABLE "tenders" DROP CONSTRAINT "FK_bc683384a04d34dff56d1bef0e5"`);
        await queryRunner.query(`ALTER TABLE "tender_categories" DROP CONSTRAINT "FK_44dd4ea9994eb8eb1486031e449"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9"`);
        await queryRunner.query(`ALTER TABLE "msme_certifications" DROP CONSTRAINT "FK_09054a14e0ffb0c677636d64e63"`);
        await queryRunner.query(`ALTER TABLE "msme_profiles" DROP CONSTRAINT "FK_41f79f9f15398d082a83cd27a41"`);
        await queryRunner.query(`ALTER TABLE "organization_invitations" DROP CONSTRAINT "FK_7f88954e8d667a76ae3ced6f446"`);
        await queryRunner.query(`ALTER TABLE "user_oauth_identities" DROP CONSTRAINT "FK_a0704331845bb831f82b54aea08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_requested_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_processed_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dsr_request_created_at"`);
        await queryRunner.query(`DROP TABLE "dsr_requests"`);
        await queryRunner.query(`DROP TYPE "public"."dsr_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."dsr_requests_request_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_resource_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_resource_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_log_created_at"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_counter_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_counter_metric"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_counter_period_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_usage_counter_period_end"`);
        await queryRunner.query(`DROP TABLE "usage_counters"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_subscription"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_issued_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_due_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_paid_at"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_subscription_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_subscription_plan"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_subscription_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_subscription_billing_cycle"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_org_subscription_next_billing"`);
        await queryRunner.query(`DROP TABLE "organization_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."organization_subscriptions_billing_cycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organization_subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscription_plan_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscription_plan_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subscription_plan_display_order"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_preference_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_preference_digest"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_preference_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_preference_push"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_digest_frequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_created_at"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_search_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_search_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_search_default"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_search_notify"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_search_last_executed"`);
        await queryRunner.query(`DROP TABLE "saved_searches"`);
        await queryRunner.query(`DROP TYPE "public"."saved_searches_sort_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bid_draft_pipeline_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bid_draft_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bid_draft_version"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bid_draft_generated_by_ai"`);
        await queryRunner.query(`DROP TABLE "bid_drafts"`);
        await queryRunner.query(`DROP TYPE "public"."bid_drafts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_pipeline_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_sort_order"`);
        await queryRunner.query(`DROP TABLE "checklist_tasks"`);
        await queryRunner.query(`DROP TYPE "public"."checklist_tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."checklist_tasks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."checklist_tasks_task_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pipeline_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pipeline_tender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pipeline_stage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pipeline_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pipeline_due_date"`);
        await queryRunner.query(`DROP TABLE "pipeline_items"`);
        await queryRunner.query(`DROP TYPE "public"."pipeline_items_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pipeline_items_stage_enum"`);
        await queryRunner.query(`DROP TABLE "eligibility_checklist_items"`);
        await queryRunner.query(`DROP TABLE "match_scores"`);
        await queryRunner.query(`DROP TABLE "tender_chunk_embeddings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_chunk_document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_chunk_index"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_chunk_page"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_chunk_language"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_chunk_checksum"`);
        await queryRunner.query(`DROP TABLE "tender_document_chunks"`);
        await queryRunner.query(`DROP TABLE "organization_profile_embeddings"`);
        await queryRunner.query(`DROP TABLE "tender_embeddings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_error_run"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_error_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_error_severity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_error_retryable"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_error_resolved"`);
        await queryRunner.query(`DROP TABLE "ingestion_errors"`);
        await queryRunner.query(`DROP TYPE "public"."ingestion_errors_severity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_run_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_run_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_run_started_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingestion_run_completed_at"`);
        await queryRunner.query(`DROP TABLE "ingestion_runs"`);
        await queryRunner.query(`DROP TYPE "public"."ingestion_runs_trigger_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ingestion_runs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_field_correction_tender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_field_correction_field"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_field_correction_source"`);
        await queryRunner.query(`DROP TABLE "tender_field_corrections"`);
        await queryRunner.query(`DROP TYPE "public"."tender_field_corrections_correction_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_tender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_uploaded_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_document_processed"`);
        await queryRunner.query(`DROP TABLE "tender_documents"`);
        await queryRunner.query(`DROP TYPE "public"."tender_documents_storage_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_link_tender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_link_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_link_primary"`);
        await queryRunner.query(`DROP TABLE "tender_category_links"`);
        await queryRunner.query(`DROP TYPE "public"."tender_category_links_assignment_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_462fa4960a4caa39f683ed4868"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a4ba8e81b180c9c248b30877c"`);
        await queryRunner.query(`DROP TABLE "tenders"`);
        await queryRunner.query(`DROP TYPE "public"."tenders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenders_tender_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_display_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_category_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fad5d6f20bd53891d842d02459"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09044ebe817cccdbcb1183468b"`);
        await queryRunner.query(`DROP TABLE "tender_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_source_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_source_country"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tender_source_auth_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d2c386db4812dc375b54ad03f"`);
        await queryRunner.query(`DROP TABLE "tender_sources"`);
        await queryRunner.query(`DROP TYPE "public"."tender_sources_authentication_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "organization_members"`);
        await queryRunner.query(`DROP TYPE "public"."organization_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_msme_certification_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_msme_certification_active"`);
        await queryRunner.query(`DROP TABLE "msme_certifications"`);
        await queryRunner.query(`DROP TABLE "msme_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dfa5b36a9305efc5b7e9f369a"`);
        await queryRunner.query(`DROP TABLE "organization_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."organization_invitations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organization_invitations_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_oauth_identities"`);
    }

}
