import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform, Type } from 'class-transformer';
import {
  IsBoolean,
  IsDateString,
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';

import { BidDraftStatus } from '@app/database/entities/pipeline/bid-draft.entity';

export class CreateBidDraftDto {
  @ApiProperty({
    description: 'Pipeline item ID',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @Transform(({ value }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsUUID()
  @IsNotEmpty()
  pipelineItemId!: string;

  @ApiPropertyOptional({
    description: 'Draft version number',
    default: 1,
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  version?: number;

  @ApiProperty({
    description: 'Bid draft title',
    maxLength: 255,
    example: 'Technical Proposal v1',
  })
  @Transform(({ value }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  title!: string;

  @ApiProperty({
    description: 'Bid draft content',
  })
  @IsString()
  @IsNotEmpty()
  content!: string;

  @ApiPropertyOptional({
    description: 'Whether this draft was generated by AI',
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  generatedByAi?: boolean;

  @ApiPropertyOptional({
    description: 'Bid draft status',
    enum: BidDraftStatus,
    default: BidDraftStatus.DRAFT,
  })
  @IsOptional()
  @IsEnum(BidDraftStatus)
  status?: BidDraftStatus;

  @ApiPropertyOptional({
    description: 'URL of the generated file',
  })
  @IsOptional()
  @Transform(({ value }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsString()
  fileUrl?: string;

  @ApiPropertyOptional({
    description: 'Submission timestamp',
  })
  @IsOptional()
  @IsDateString()
  submittedAt?: string;

  @ApiPropertyOptional({
    description: 'User ID who created the draft',
  })
  @IsOptional()
  @Transform(({ value }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsUUID()
  createdByUserId?: string;
}
